### ISSUE TITLE
Build pipeline cleanup

### ISSUE THREAD

**Issue by balloob** [home-assistant/home-assistant-polymer#1176]
Extracted from #1154. Pull requests for all these are welcome! (1 PR per feature)

 - [ ] Move `src/util/*` into `src/common/`
 - [ ] Remove any unnecessary curly braces around module code ([example](https://github.com/home-assistant/home-assistant-polymer/blob/81fbda49bd6a0179e73dbe2d1e79d1e713c10fda/src/cards/ha-camera-card.js#L10))
 - [x] Use NPM package `@mdi/svg` to fetch MDI icons and create `<hass-iconset-svg>` and import as js
 - [ ] Code Split inside config panel.

## Webpack plugins to explore

 - [x] Replace gzip step with [webpack-compress-plugin](https://github.com/webpack-contrib/compression-webpack-plugin)

### Done

 - [ ] ~~Code split states panel and load using `partial-panel-resolver` ?~~ Needs more thought, hurts initial load too much
 - [x] Get rid of anything stored on the window that is not `window.Polymer`. Examples: `window.hassAttributeUtil`, `window.HassMediaPlayerEntity`, `window.stateHistoryCache`, `window.CoverEntity`, `window.getTranslation`
 - [x] Convert CoverEntity and MediaPlayerEntity to classes
 - [x] Do not include all the locales when bundling moment for the charts
 - [x] Exclude `@polymer/paper-styles/color.js` and `@polymer/font-roboto` from bundling
 - [ ] ~~Build index.html with HTML Webpack Plugin ?~~ Won't work with theme color and hashing mdi.html
 - [ ] ~~Minify HTML/CSS inside JS~~ not possible
 - [x] Add Service Worker back or at least restore the HTML5 push notifications part
 - [x] Hassio panel #1184
 - [x] remove dependency on rollup for building parts of the JS (partly done in #1177) #1179
 - [ ] ~~Deprecate Custom panels in HTML~~ done when JS panels are supported.
 - [ ] ~~Add support for custom panels in JS~~ planning a more extensive solution that can also handle hass.io
 - [x] Move panels folder into src #1183
 - [x] Replace all references to hassUtil with direct imports ([example](https://github.com/home-assistant/home-assistant-polymer/pull/1154/commits/5ea3703d0842ac11cff4ddd263a70029f6c5d2fb))
 - [x] Remove all `static get is()` and just pass name into `customElements.define`
 - [ ] ~~Explore using babel-minify for minification ([use these options](https://github.com/Polymer/tools/blob/master/packages/build/src/js-transform.ts#L100-L115))~~ sticking with uglifyjs for now
 - [ ] ~~Add es5 custom elements adapter to app.js using [webpack-concat-plugin](https://github.com/hxlniada/webpack-concat-plugin)~~ can we write a small bootstrap script instead with dynamic imports?
 - [x] Don't use `gutil.File` ([info](https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5#635d)) #1185
 - [x] split mixins into separate files #1183
 - [x] code split more info out
 - [x] code split conversation out
 - [x] remove unused gulp files #1185

**Comment by c727** [comment]
[ ] Some iron-icons disappear after normal F5

**Comment by fanthos** [comment]
Not sure the html template could be minified or not by using `polymer-build` tool.

**Comment by balloob** [comment]
We can't migrate templating language, we're still using Polymer. Looks like Polymer itself hasn't figured it out yet so we're not going to minify.

For future components we're going to switch to [Lit Element](https://www.npmjs.com/package/@polymer/lit-element)

**Comment by fanthos** [comment]
For moment.js, we can just ignore the locale files and it works great.

**Comment by balloob** [comment]
added it to the list

**Comment by balloob** [comment]
Funny, the IgnorePlugin has as example to exclude the moment locales https://webpack.js.org/plugins/ignore-plugin/#ignore-moment-locales
