### ISSUE TITLE
Lovelace 0.73 to-do

### ISSUE THREAD

**Issue by c727** [home-assistant/home-assistant-polymer#1382]
- [ ] hui-image: remove redundant state_image.default -> use image instead #1386
- [x] rework filter to use a predefined entities list. Bonus: support entities defined as object (requires changes also in entities and picture-glance) https://github.com/home-assistant/home-assistant-polymer/pull/1387
- [ ] replace horizontal stack with a card that shows hui-images instead

**Comment by balloob** [comment]
I would suggest we wait with replacing the horizontal stack. It is still a nice card for smaller custom cards.
