### ISSUE TITLE
[Gallery] to-do

### ISSUE THREAD

**Issue by c727** [home-assistant/home-assistant-polymer#1480]
- [x] fix map `Refused to apply style from 'http://localhost:8080/static/images/leaflet/leaflet.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.`
- [x] ~~fix #card width for iframe (max-width doesn't work atm)~~
- [ ] camera picture support
- [x] entity_picture support
- [x] toggle state support
- [x] fix entities card header toggle
- [x] fix translations (e.g. button caption n.a.)
- [x] fix last-changed in entities card
- [x] GET https://deploy-preview-1481--home-assistant-lovelace-gallery.netlify.com/static/images/image-broken.svg 404 ()

**Comment by balloob** [comment]
The `demo_dump.js` data is getting outdated because of the timestamps. However, we've solved this problem before 😉 [demo_data/state_data.js](https://github.com/home-assistant/home-assistant-polymer/blob/master/demo_data/state_data.js#L1-L16)

We should use that. Instead of converting `demo_dump.js`, we should give each demo only the states that it needs (we still want to share hass between all cards within 1 demo). Will be easier with `#1489`
