### ISSUE TITLE
Ensure no Polymer elements used in base bundle

### ISSUE THREAD

**Issue by balloob** [home-assistant/home-assistant-polymer#2096]
The Home Assistant app shell (sidebar, panel rendered) should not rely on any polymer elements. Goal of this issue is that Home Assistant doesn't include Polymer elements, not the dependencies (that's for another issue).

To do:

- [x] src/layouts/home-assistant-main.js #2648 
- [x] util/ha-url-sync.js #2824 
- [x] ~~dialogs/ha-voice-command-dialog.js~~ no longer part of base bundle #2658 
- [x] hass-loading-screen #2742 
- [x] ha-menu-button #2825

**Comment by iantrich** [comment]
🎉
