### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by balloob** [home-assistant/home-assistant-polymer#369]
While migrating to polymer-build I came to the conclusion that our build of the frontend is a real mess. We can do better 👍 

Migrating to polymer-build required some hacks but now that it's in, it will be a good first step to a better future. Here are the following steps:

 - [x] Use polymer-build so that we can use ES2015 (requirement for Polymer 2) - #344 
 - [x] Upgrade to Polymer 2 - #308
 - [x] Consolidate all frontend pieces in `home-assistant-polymer`.
    - Migrate static folder from `home-assistant` to `home-assistant-polymer`
    - For PyPi packages, include `home-assistant-polymer/build`.
    - Generate gzip in gulp task
    - Generate version MD5 hashes in gulp task and store in versions.json in `build/`. Update frontend.py to read versions from there.

Side tasks for the frontend:

 - [x] Migrate hass.io panel gulp task from vulcanize to polymer-build
 - [ ] Migrate gen-service-worker gulp task to be a real gulp task, fix minifying the code?
 - [x] Start migrating components to extend Polymer.Element (depends on Polymer 2, requires Hass.io being migrated)
 - [ ] Migrate from deprecated paper-drawer-panel to use app-layout https://github.com/PolymerElements/paper-drawer-panel
 - [ ] Use external babel-helpers for bundle.

~~When the migration of hass.io panel to polymer-build is done, we can start using ES2015 in our web components. We cannot use it before that because the hass.io panel build script uses Vulcanize which is not ES2015 compatible.~~
