### ISSUE TITLE
[to-do/ issues] new hassio panel

### ISSUE THREAD

**Issue by c727** [home-assistant/home-assistant-polymer#912]
- [x] remove hacks with time zone for snapshots (should be fixed now on snapshot creation)
- [x] center snapshot dialog
- [x] backdrop for snapshot dialog
- [ ] rework add-on details
- [ ] add some code for a small number of cards
- [ ] JS dialogs not working in iOS app
- [x] use variables for colors: https://github.com/home-assistant/home-assistant-polymer/issues/913
- [x] reload snapshots and local add-ons (if copied new files to the folders)
- [ ] scroll to top if tab changes
- [x] use ha-style-dialog
~~- [ ] combine both snapshot restore buttons (if possible)~~
- [x] use papaer-dialog-scrollable for add-ons in snapshot dialog
- [ ] snapshot upload

**Comment by balloob** [comment]
The issue with centering the dialog is that the dialog is centered when there is no data yet. Then when the data arrives, the height/width change and it looks a bit weird. Fix it by firing an `iron-resize` event after loading the data. Make sure you do it after the next paint (by calling rAF twice) so that the browser has time to paint the new DOM.

**Comment by NovapaX** [comment]
Is it possible to make a basic ha-polymer-element and drop-in function to replace javascript `confirm` ?
Could be useful I guess.

**Comment by c727** [comment]
This PR includes something we can use https://github.com/home-assistant/home-assistant-polymer/pull/845

**Comment by NovapaX** [comment]
Yes, for now only the iOS app is affected, so I'd just wait for that to get merged before going forward on the dialog, so you can reuse the element.

**Comment by plutosherry** [comment]
The hass.io panel cannot be opened, and the log false information is as follows:
`2018-02-26 11:33:46 ERROR (MainThread) [frontend.js.latest.201802090] http://192.168.1.9:8123/frontend_latest/panels/ha-panel-hassio-ad7aa9a6055f74475fd3ba2c00bfe512.html:1:829 Uncaught TypeError: Cannot read property 'setProperties' of null`

**Comment by balloob** [comment]
@plutosherry browser version? and did you try refreshing your browser?

**Comment by plutosherry** [comment]
@balloob  I try to use IE browser version 11, Google browsers(chrome 64.0.3282.167), and Microsoft edge(41.16299.248.0), but neither can open hass.io panel

**Comment by c727** [comment]
@plutosherry
can you check chrome browsers developer console for errors, please?

**Comment by plutosherry** [comment]
@c727  OK, I'll try it later.

**Comment by plutosherry** [comment]
The link address is 'http://192.168.1.9:8123/frontend_latest/panels/ha-panel-hassio-ad7aa9a6055f74475fd3ba2c00bfe512.html'

`ha-panel-hassio-ad7aa9a6055f74475fd3ba2c00bfe512.html:1 Uncaught TypeError: Cannot read property 'setProperties' of null
    at HTMLElement._updateProperties (ha-panel-hassio-ad7aa9a6055f74475fd3ba2c00bfe512.html:1)
    at setTimeout (ha-panel-hassio-ad7aa9a6055f74475fd3ba2c00bfe512.html:1)
_updateProperties @ ha-panel-hassio-ad7aa9a6055f74475fd3ba2c00bfe512.html:1
setTimeout @ ha-panel-hassio-ad7aa9a6055f74475fd3ba2c00bfe512.html:1
setTimeout (async)
_updateProperties @ ha-panel-hassio-ad7aa9a6055f74475fd3ba2c00bfe512.html:1
setTimeout @ ha-panel-hassio-ad7aa9a6055f74475fd3ba2c00bfe512.html:1
setTimeout (async)
_updateProperties @ ha-panel-hassio-ad7aa9a6055f74475fd3ba2c00bfe512.html:1
setTimeout @ ha-panel-hassio-ad7aa9a6055f74475fd3ba2c00bfe512.html:1
setTimeout (async)
_updateProperties @ ha-panel-hassio-ad7aa9a6055f74475fd3ba2c00bfe512.html:1
setTimeout @ ha-panel-hassio-ad7aa9a6055f74475fd3ba2c00bfe512.html:1
setTimeout (async)
_updateProperties @ ha-panel-hassio-ad7aa9a6055f74475fd3ba2c00bfe512.html:1
setTimeout @ ha-panel-hassio-ad7aa9a6055f74475fd3ba2c00bfe512.html:1
setTimeout (async)
_updateProperties @ ha-panel-hassio-ad7aa9a6055f74475fd3ba2c00bfe512.html:1
setTimeout @ ha-panel-hassio-ad7aa9a6055f74475fd3ba2c00bfe512.html:1
setTimeout (async)
_updateProperties @ ha-panel-hassio-ad7aa9a6055f74475fd3ba2c00bfe512.html:1
setTimeout @ ha-panel-hassio-ad7aa9a6055f74475fd3ba2c00bfe512.html:1
setTimeout (async)
_updateProperties @ ha-panel-hassio-ad7aa9a6055f74475fd3ba2c00bfe512.html:1
setTimeout @ ha-panel-hassio-ad7aa9a6055f74475fd3ba2c00bfe512.html:1
setTimeout (async)
_updateProperties @ ha-panel-hassio-ad7aa9a6055f74475fd3ba2c00bfe512.html:1
setTimeout @ ha-panel-hassio-ad7aa9a6055f74475fd3ba2c00bfe512.html:1
setTimeout (async)
_updateProperties @ ha-panel-hassio-ad7aa9a6055f74475fd3ba2c00bfe512.html:1
setTimeout @ ha-panel-hassio-ad7aa9a6055f74475fd3ba2c00bfe512.html:1
setTimeout (async)
_updateProperties @ ha-panel-hassio-ad7aa9a6055f74475fd3ba2c00bfe512.html:1
setTimeout @ ha-panel-hassio-ad7aa9a6055f74475fd3ba2c00bfe512.html:1
setTimeout (async)
_updateProperties @ ha-panel-hassio-ad7aa9a6055f74475fd3ba2c00bfe512.html:1
setTimeout @ ha-panel-hassio-ad7aa9a6055f74475fd3ba2c00bfe512.html:1
setTimeout (async)
_updateProperties @ ha-panel-hassio-ad7aa9a6055f74475fd3ba2c00bfe512.html:1
setTimeout @ ha-panel-hassio-ad7aa9a6055f74475fd3ba2c00bfe512.html:1
setTimeout (async)
_updateProperties @ ha-panel-hassio-ad7aa9a6055f74475fd3ba2c00bfe512.html:1
setTimeout @ ha-panel-hassio-ad7aa9a6055f74475fd3ba2c00bfe512.html:1
setTimeout (async)
_updateProperties @ ha-panel-hassio-ad7aa9a6055f74475fd3ba2c00bfe512.html:1
setTimeout @ ha-panel-hassio-ad7aa9a6055f74475fd3ba2c00bfe512.html:1
setTimeout (async)
_updateProperties @ ha-panel-hassio-ad7aa9a6055f74475fd3ba2c00bfe512.html:1
setTimeout @ ha-panel-hassio-ad7aa9a6055f74475fd3ba2c00bfe512.html:1
setTimeout (async)
_updateProperties @ ha-panel-hassio-ad7aa9a6055f74475fd3ba2c00bfe512.html:1
setTimeout @ ha-panel-hassio-ad7aa9a6055f74475fd3ba2c00bfe512.html:1
setTimeout (async)
_updateProperties @ ha-panel-hassio-ad7aa9a6055f74475fd3ba2c00bfe512.html:1
setTimeout @ ha-panel-hassio-ad7aa9a6055f74475fd3ba2c00bfe512.html:1
setTimeout (async)
_updateProperties @ ha-panel-hassio-ad7aa9a6055f74475fd3ba2c00bfe512.html:1
setTimeout @ ha-panel-hassio-ad7aa9a6055f74475fd3ba2c00bfe512.html:1
setTimeout (async)
_updateProperties @ ha-panel-hassio-ad7aa9a6055f74475fd3ba2c00bfe512.html:1
setTimeout @ ha-panel-hassio-ad7aa9a6055f74475fd3ba2c00bfe512.html:1
setTimeout (async)
_updateProperties @ ha-panel-hassio-ad7aa9a6055f74475fd3ba2c00bfe512.html:1
setTimeout @ ha-panel-hassio-ad7aa9a6055f74475fd3ba2c00bfe512.html:1
setTimeout (async)
_updateProperties @ ha-panel-hassio-ad7aa9a6055f74475fd3ba2c00bfe512.html:1
setTimeout @ ha-panel-hassio-ad7aa9a6055f74475fd3ba2c00bfe512.html:1
setTimeout (async)
_updateProperties @ ha-panel-hassio-ad7aa9a6055f74475fd3ba2c00bfe512.html:1
setTimeout @ ha-panel-hassio-ad7aa9a6055f74475fd3ba2c00bfe512.html:1
setTimeout (async)
_updateProperties @ ha-panel-hassio-ad7aa9a6055f74475fd3ba2c00bfe512.html:1
setTimeout @ ha-panel-hassio-ad7aa9a6055f74475fd3ba2c00bfe512.html:1
setTimeout (async)
_updateProperties @ ha-panel-hassio-ad7aa9a6055f74475fd3ba2c00bfe512.html:1
setTimeout @ ha-panel-hassio-ad7aa9a6055f74475fd3ba2c00bfe512.html:1
setTimeout (async)
_updateProperties @ ha-panel-hassio-ad7aa9a6055f74475fd3ba2c00bfe512.html:1
setTimeout @ ha-panel-hassio-ad7aa9a6055f74475fd3ba2c00bfe512.html:1
setTimeout (async)
_updateProperties @ ha-panel-hassio-ad7aa9a6055f74475fd3ba2c00bfe512.html:1
setTimeout @ ha-panel-hassio-ad7aa9a6055f74475fd3ba2c00bfe512.html:1
setTimeout (async)
_updateProperties @ ha-panel-hassio-ad7aa9a6055f74475fd3ba2c00bfe512.html:1
setTimeout @ ha-panel-hassio-ad7aa9a6055f74475fd3ba2c00bfe512.html:1
setTimeout (async)
_updateProperties @ ha-panel-hassio-ad7aa9a6055f74475fd3ba2c00bfe512.html:1
setTimeout @ ha-panel-hassio-ad7aa9a6055f74475fd3ba2c00bfe512.html:1
setTimeout (async)
_updateProperties @ ha-panel-hassio-ad7aa9a6055f74475fd3ba2c00bfe512.html:1
setTimeout @ ha-panel-hassio-ad7aa9a6055f74475fd3ba2c00bfe512.html:1
setTimeout (async)
_updateProperties @ ha-panel-hassio-ad7aa9a6055f74475fd3ba2c00bfe512.html:1
setTimeout @ ha-panel-hassio-ad7aa9a6055f74475fd3ba2c00bfe512.html:1
setTimeout (async)
_updateProperties @ ha-panel-hassio-ad7aa9a6055f74475fd3ba2c00bfe512.html:1
setTimeout @ ha-panel-hassio-ad7aa9a6055f74475fd3ba2c00bfe512.html:1
setTimeout (async)
_updateProperties @ ha-panel-hassio-ad7aa9a6055f74475fd3ba2c00bfe512.html:1
setTimeout @ ha-panel-hassio-ad7aa9a6055f74475fd3ba2c00bfe512.html:1`

**Comment by NovapaX** [comment]
the link to open the Hassio panel, in your case, should just be: http://192.168.1.9:8123hassio

**Comment by plutosherry** [comment]
@balloob I followed sudo apt-get update & sudo apt-get upgrade and restarted raspi, and everything returned to normal. I don't know why, in a word, hass.io panel is normal

**Comment by metbril** [comment]
Documentation is not in line with new UI, for example

https://home-assistant.io/hassio/installing_third_party_addons/

still shows the shopping bag icon

**Comment by bramkragten** [comment]
The button to restart home assistant (would fire `hassio homeassistant restart`) was removed with the new layout, what was the reason for this change? I used it a lot because it works better/more reliable/ than the restart button in settings...

**Comment by c727** [comment]
It's redundant as it's the same as restart in config-panel "now"

**Comment by cgarwood** [comment]
Closing in favor of #1710
